### ISSUE TITLE
Sometimes the login works and sometimes it doesn't

### ISSUE THREAD

**Issue by xanto521** [dimkouv/protonmail-cli#20]
[root@localhost protonmail-cli]# python3 example.py 
[INFO] 2019-06-19 19:18:51: Initiating ProtonMail client
xdpyinfo was not found, X start can not be checked! Please install xdpyinfo!
[INFO] 2019-06-19 19:18:55: Logging in...
[INFO] 2019-06-19 19:19:35: Logged in successfully
Traceback (most recent call last):
  File "example.py", line 21, in <module>
    as_html=True
  File "/root/protonmail-cli/protonmail/core.py", line 404, in send_mail
    """ % (message.replace('"', '\\"')))
  File "/usr/python3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "/usr/python3/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/python3/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: SyntaxError: "" string literal contains an unescaped line break

##################
This was successful login, but I made an error when I sent the HTML email, and it was ok when I sent the text,

**Comment by xanto521** [comment]
[root@localhost protonmail-cli]# python3 example.py 
[INFO] 2019-06-19 19:17:33: Initiating ProtonMail client
xdpyinfo was not found, X start can not be checked! Please install xdpyinfo!
[INFO] 2019-06-19 19:17:33: Unable to initiate Protonmail Client. Reason: Message: invalid argument: can't kill an exited process

[INFO] 2019-06-19 19:17:33: Logging in...
[INFO] 2019-06-19 19:17:33: Login failed!
Traceback (most recent call last):
  File "/root/protonmail-cli/protonmail/core.py", line 55, in login
    self.web_driver.get(variables.url)
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 4, in <module>
    client.login("************", "****************")
  File "/root/protonmail-cli/protonmail/core.py", line 96, in login
    raise Exception("Unable to login")
Exception: Unable to login

#################
This is a login failure

**Comment by dimkouv** [comment]
1. What is the HTML string that you're trying to send?
2. Can you show me the code in example.py? Maybe an unterminated client is causing this issue.

Also, try reinstalling using `pip install git+https://github.com/dimkouv/protonmail-cli`

**Comment by xanto521** [comment]
I can now use SMTP, but only on Windows, and in the selenium way on Linux, your code is still worth considering, thank you
