### ISSUE TITLE
Selenium error

### ISSUE THREAD

**Issue by ai2010** [dimkouv/protonmail-cli#30]
Hello I am testing the library and when I run core_test.py I got:

```
======================================================================
ERROR: test_3_has_new_mail (__main__.CoreTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "protonmail-cli/tests/core_test.py", line 56, in test_3_has_new_mail
    self.client.has_new_mail()
  File "/home/andrea/.local/lib/python3.6/site-packages/protonmail/core.py", line 282, in has_new_mail
    for m in mails:
TypeError: 'NoneType' object is not iterable

======================================================================
ERROR: test_5_send_mail_html (__main__.CoreTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "protonmail-cli/tests/core_test.py", line 77, in test_5_send_mail_html
    "[Success] This message was automatically send from <h1>protonmail-cli</h1> tests."
  File "/home/andrea/.local/lib/python3.6/site-packages/protonmail/core.py", line 420, in send_mail
    el.click()
  File "/home/andrea/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/andrea/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/andrea/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/andrea/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class="pm_button primary mobileFull composer-btn-send btnSendMessage-btn-action"> is not clickable at point (1154,575) because another element <div class="pull-right"> obscures it


======================================================================
FAIL: test_2_get_mails (__main__.CoreTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "protonmail-cli/tests/core_test.py", line 42, in test_2_get_mails
    "[%s] unable to load conversation wrapper" % page)
AssertionError: [inbox] unable to load conversation wrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "protonmail-cli/tests/core_test.py", line 52, in test_2_get_mails
    (page, str(e)))
AssertionError: [inbox] unable to read any mail error: [inbox] unable to load conversation wrapper

----------------------------------------------------------------------
Ran 7 tests in 80.012s

FAILED (failures=1, errors=2)
```

**Comment by dimkouv** [comment]
@ai2010 I think there was an update on protonmail's UI so the css selectors should be updated. I'll work on it this weekend. Thank you.

**Comment by dimkouv** [comment]
@ai2010 everything's working fine at this point of time.

**Comment by kemonprogrammer** [comment]
Hi, I tried to use the client (not test it), but got the same error
[Here is the link to the gist](https://gist.github.com/kemonprogrammer/9dc8f103c5195caf39b6957d02a7485b)

Do you know how I can fix it? And should I open a new issue for this?
